plugins {
    id 'io.nextflow.nextflow-plugin' version '1.0.0-beta.10'
}

version = '0.2.0'

nextflowPlugin {
    nextflowVersion = '25.10.0'

    provider = 'nvnieuwk'
    className = 'nvnieuwk.teams.TeamsPlugin'
    extensionPoints = [
        'nvnieuwk.teams.configuration.TeamsConfiguration',
        'nvnieuwk.teams.TeamsExtension',
        'nvnieuwk.teams.TeamsFactory'
    ]

}
